/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.MemberBUS;
import BUS.ViolationBUS;
import Entity.Member;
import Entity.Violation;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author nqk09
 */
public class ViolationExcelGUI extends javax.swing.JFrame {

    ArrayList<Violation> violations = new ArrayList<>();
    ArrayList<Violation> successList = new ArrayList<>();
    ViolationBUS violationBUS = new ViolationBUS();
    MemberBUS memberBUS = new MemberBUS();
    Member member = new Member();

    public ViolationExcelGUI(ArrayList<Violation> list) {
        initComponents();
        setDefaultCloseOperation(HIDE_ON_CLOSE);
        setLocationRelativeTo(null);
        this.violations = list;
        loadDataToTable(violations);
        tableCustomizer();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton_Add = new javax.swing.JButton();
        jButton_Cancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Violation = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1050, 770));

        jButton_Add.setBackground(new java.awt.Color(255, 0, 0));
        jButton_Add.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_Add.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Add.setText("Thêm");
        jButton_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddActionPerformed(evt);
            }
        });

        jButton_Cancel.setBackground(new java.awt.Color(51, 51, 51));
        jButton_Cancel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_Cancel.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Cancel.setText("Hủy");
        jButton_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelActionPerformed(evt);
            }
        });

        jScrollPane1.setMinimumSize(new java.awt.Dimension(899, 532));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(899, 532));

        jTable_Violation.setAutoCreateRowSorter(true);
        jTable_Violation.setBackground(new java.awt.Color(255, 255, 255));
        jTable_Violation.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTable_Violation.setForeground(new java.awt.Color(0, 0, 0));
        jTable_Violation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_Violation.setMinimumSize(new java.awt.Dimension(899, 532));
        jTable_Violation.setPreferredSize(new java.awt.Dimension(899, 532));
        jTable_Violation.setRowHeight(36);
        jScrollPane1.setViewportView(jTable_Violation);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Thêm dữ liệu với file Excel");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(302, 302, 302))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(jButton_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(66, 66, 66))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 619, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddActionPerformed
        int success = 0;
        int errors = 0;
        ArrayList<Violation> listErr = new ArrayList<>();
        for (Violation violation : successList) {
            try {
                violationBUS.CreateViolation(violation);
                success++;
            } catch (Exception e) {
                errors++;
                listErr.add(violation);
            }
        }
        if (errors > 0) {
            JOptionPane.showMessageDialog(this, "Thêm thành công " + success + "\nThêm thất bại " + errors + "\nNhững dữ liệu thêm thất bại hiển thị trong bảng!");
            loadDataToTable(listErr);
            tableCustomizer();
        } else {
            JOptionPane.showMessageDialog(this, "Thêm thành công!");
        }
    }//GEN-LAST:event_jButton_AddActionPerformed

    private void jButton_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelActionPerformed
        int result = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn hủy?", "Hủy", JOptionPane.YES_NO_OPTION);
        if (result == 0) {
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton_CancelActionPerformed

    /**
     * @param args the command line arguments
     */
    private void tableCustomizer() {
        JTableHeader header = jTable_Violation.getTableHeader();
        header.setPreferredSize(new Dimension(header.getPreferredSize().width, 36));
        header.setFont(new Font("Segoe UI", Font.PLAIN, 16));
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                setBorder(BorderFactory.createLineBorder(Color.WHITE));
                setHorizontalAlignment(JLabel.CENTER);
                return this;
            }
        };
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        jTable_Violation.setDefaultRenderer(String.class, centerRenderer);
        headerRenderer.setBackground(new Color(0, 102, 255));
        headerRenderer.setForeground(Color.WHITE);
        for (int i = 0; i < jTable_Violation.getModel().getColumnCount(); i++) {
            jTable_Violation.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }
        jTable_Violation.getColumnModel().getColumn(5).setPreferredWidth(40);
        jTable_Violation.getColumnModel().getColumn(4).setPreferredWidth(30);
        jTable_Violation.getColumnModel().getColumn(0).setPreferredWidth(40);
    }

    private void loadDataToTable(ArrayList<Violation> listExcel) {
        Collections.sort(listExcel, Comparator.comparingInt(Violation::getViolationId));
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Mã vi phạm");
        model.addColumn("Mã thành viên");
        model.addColumn("Tên thành viên");
        model.addColumn("Hình thức xử lý");
        model.addColumn("Số tiền");
        model.addColumn("Trạng thái");
        jTable_Violation.setModel(model);
        for (Violation violation : listExcel) {
            try {
                member = memberBUS.getAMemberWithID(Long.parseLong(violation.getMemberId().toString()));
                model.addRow(new Object[]{violation.getViolationId(), violation.getMemberId(), member.getHoTen(), violation.getHadlingType(), violation.getFine(), violation.getStatus()});
                successList.add(violation);
            } catch (Exception e) {
                System.out.println(violation.getMemberId().toString() + "  " + e);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Add;
    private javax.swing.JButton jButton_Cancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Violation;
    // End of variables declaration//GEN-END:variables
}
