/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.ViolationBUS;
import DAL.ViolationDAL;
import BUS.MemberBUS;
import Entity.Member;
import Entity.Violation;
import static GUI.Violation_AddGUI.isNumber;
import enums.Punishment;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author nqk09
 */
public class Violation_EditGUI extends javax.swing.JFrame {

    ViolationDAL violationDAL = new ViolationDAL();
    ViolationBUS violationBUS = new ViolationBUS(violationDAL);
    MemberBUS memberBUS = new MemberBUS();
    ArrayList<Member> listMember = (ArrayList<Member>) memberBUS.getAllMembers();
    int violationID;
    int memberID;

    /**
     * Creates new form Violation_EditGUI
     */
    public Violation_EditGUI(int violationId, int memberId) {
        initComponents();
        this.violationID = violationId;
        this.memberID = memberId;
        setDefaultCloseOperation(HIDE_ON_CLOSE);
        setLocationRelativeTo(null);
        loadComboboxData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_Name = new javax.swing.JTextField();
        jTextField_Money = new javax.swing.JTextField();
        jCheckBox = new javax.swing.JCheckBox();
        jButton_clean = new javax.swing.JButton();
        jButton_add = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox_Id = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(660, 450));
        jPanel2.setPreferredSize(new java.awt.Dimension(530, 404));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Sửa thông tin vi phạm");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Mã thành viên:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Họ và tên:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Hình thức xử lý:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Số tiền:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Ngày xử lý:");

        jTextField_Name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTextField_Money.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jCheckBox.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jCheckBox.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox.setText("Đã xử lý");

        jButton_clean.setBackground(new java.awt.Color(233, 233, 233));
        jButton_clean.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_clean.setForeground(new java.awt.Color(0, 0, 0));
        jButton_clean.setText("Làm sạch");
        jButton_clean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cleanActionPerformed(evt);
            }
        });

        jButton_add.setBackground(new java.awt.Color(0, 102, 255));
        jButton_add.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_add.setForeground(new java.awt.Color(255, 255, 255));
        jButton_add.setText("Sửa");
        jButton_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jComboBox_Id.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_Id.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_IdItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jTextField_Name, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                            .addComponent(jTextField_Money, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox_Id, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jButton_clean)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(jButton_add, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(225, 225, 225))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Money, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_clean)
                    .addComponent(jButton_add)
                    .addComponent(jCheckBox))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_cleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cleanActionPerformed
        jComboBox_Id.setSelectedIndex(-1);
        jTextField_Money.setText("");
        jCheckBox.setSelected(false);
        jDateChooser1.setDate(null);
    }//GEN-LAST:event_jButton_cleanActionPerformed

    private void jButton_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addActionPerformed
        ArrayList<Violation> list = (ArrayList<Violation>) violationBUS.GetViolationListByFilter(null, null, null);
        Collections.sort(list, Comparator.comparingInt(Violation::getViolationId));
        if (checkInput() == 1) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đủ thông tin!");
        } else if (checkInput() == 2) {
            JOptionPane.showMessageDialog(this, "Số tiền phải là số!");
        } else {
            Date date = jDateChooser1.getDate();
            java.sql.Date sqlDate = new java.sql.Date(date.getTime());
            int status = 0;
            if (jCheckBox.isSelected()) {
                status = 1;
            }
            Violation violation = new Violation();
            if (jTextField_Money.getText().isEmpty()) {
                violation = new Violation(violationID, Integer.parseInt(jComboBox_Id.getSelectedItem().toString()), jComboBox1.getSelectedItem().toString(), null, sqlDate, status);
            } else {
                violation = new Violation(violationID, Integer.parseInt(jComboBox_Id.getSelectedItem().toString()), jComboBox1.getSelectedItem().toString(), Integer.parseInt(jTextField_Money.getText()), sqlDate, status);
            }
            try {
                violationBUS.ChangeStatusOfViolation(violation);
                JOptionPane.showMessageDialog(this, "Sửa thành công!");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Sửa thất bại!");
            }
        }
    }//GEN-LAST:event_jButton_addActionPerformed

    private void jComboBox_IdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_IdItemStateChanged
        for (Member member : listMember) {
            if (jComboBox_Id.getSelectedIndex() >= 0) {
                if (jComboBox_Id.getSelectedItem().toString().equals(member.getMaTV().toString())) {
                    jTextField_Name.setText(member.getHoTen());
                }
            }
        }
    }//GEN-LAST:event_jComboBox_IdItemStateChanged

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        if (jComboBox1.getSelectedIndex() == 1 || jComboBox1.getSelectedIndex() == 2 || jComboBox1.getSelectedIndex() == 5) {
            jTextField_Money.setText("");
            jTextField_Money.setEditable(false);
        } else if (jComboBox1.getSelectedIndex() == 0 || jComboBox1.getSelectedIndex() == 3 || jComboBox1.getSelectedIndex() == 4) {
            jTextField_Money.setEditable(true);
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    /**
     * @param args the command line arguments
     */
    private void loadComboboxData() {
        jComboBox1.removeAllItems();
        jComboBox_Id.removeAllItems();

        Punishment punishment = new Punishment();
        ArrayList<String> list = punishment.getPunishment();
        for (String string : list) {
            jComboBox1.addItem(string);
        }
        int count = 0;
        int mock = 0;
        for (Member member : listMember) {
            jComboBox_Id.addItem(member.getMaTV().toString());
            if (member.getMaTV() == memberID) {
                mock = count;
            }
            count++;
        }
        jTextField_Name.setText(listMember.get(0).getHoTen());
        jComboBox_Id.setSelectedIndex(mock);
    }

    private int checkInput() {
        if (jComboBox_Id.getSelectedIndex() < 0 || jTextField_Name.getText().isEmpty() || ((JTextField) jDateChooser1.getDateEditor().getUiComponent()).getText().isEmpty()) {
            return 1;
        } else if ((jComboBox1.getSelectedIndex() == 0 || jComboBox1.getSelectedIndex() == 3 || jComboBox1.getSelectedIndex() == 4) && jTextField_Money.getText().isEmpty()) {
            return 1;
        }
        if ((jComboBox1.getSelectedIndex() == 0 || jComboBox1.getSelectedIndex() == 3 || jComboBox1.getSelectedIndex() == 4) && !isNumber(jTextField_Money.getText())) {
            return 2;
        }
        return 0;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_add;
    private javax.swing.JButton jButton_clean;
    private javax.swing.JCheckBox jCheckBox;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox_Id;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField_Money;
    private javax.swing.JTextField jTextField_Name;
    // End of variables declaration//GEN-END:variables
}
